### ISSUE TITLE
issue running with vagrant

### ISSUE THREAD

**Issue by taivu** [basaltinc/theme-tools#9]
my setup is Mac El Capitan, running vagrant. vagrant's vhosts folder is linked to a folder on Mac side (/user/documents/sandbox/sites/)

steps i did:
1.) `vagrant ssh` into box, `cd` into vhosts, `git clone` this repo
2.) `npm install` then `npm run bootstrap`
3.) `cd` into `examples/common` and ran `npm install`.

running the latest node, npm, and gulp-cli globally.
here is my output:
```
vagrant@sandbox: /var/www/vhosts/learn/pub/theme-tools/examples/common
$ npm install
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm WARN deprecated swig@1.4.0: This package is no longer maintained
npm WARN /var/www/vhosts/learn/pub/theme-tools/packages/core/node_modules/node-notifier is not a child of /va
r/www/vhosts/learn/pub/theme-tools/examples/common
npm ERR! path /var/www/vhosts/learn/pub/theme-tools/examples/common/node_modules/.staging/node-notifier-18817
985
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall rename
npm ERR! enoent ENOENT: no such file or directory, rename '/var/www/vhosts/learn/pub/theme-tools/examples/com
mon/node_modules/.staging/node-notifier-18817985' -> '/var/www/vhosts/learn/pub/theme-tools/packages/core/nod
e_modules/node-notifier'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/vagrant/.npm/_logs/2017-06-21T14_40_39_386Z-debug.log
```

**Comment by taivu** [comment]
also, running `npm start` in `examples/common` yields this:
```
vagrant@sandbox: /var/www/vhosts/learn/pub/theme-tools/examples/common
$  npm start

> common@0.4.2 start /var/www/vhosts/learn/pub/theme-tools/examples/common
> gulp

module.js:472
    throw err;
    ^

Error: Cannot find module 'gulp'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/var/www/vhosts/learn/pub/theme-tools/packages/plugin-sass/sass.js:3:14)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! common@0.4.2 start: `gulp`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the common@0.4.2 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/vagrant/.npm/_logs/2017-06-21T14_56_21_703Z-debug.log
```

i think it may be related to symlinks?
looking in `examples/common/node_packages/@theme-tools/` are symlinks that take me to plugins in `packages/plugin-*`. buuut, its not complaining about that. its complaining about gulp.

**Comment by EvanLovely** [comment]
What happens when you clone the repo, and then only run `npm install` in `examples/common`? So don't run `npm install` nor `npm run bootstrap` in the root of the repo.
